"""Firestore status tracking for manual reprocess-buffer runs.

Lets the /reconcile page (sbic-manual-trigger-page, via rgmc-bc-api) show whether a
reprocess it triggered is still ongoing, finished, or errored — instead of only
inferring progress from watching the buffered-order count change.

Collection name: reprocess_runs_{env}  (e.g. reprocess_runs_production)
Document ID   : run_id, generated by rgmc-gcp-api's POST /customerpoul/reprocess-buffer
                and threaded through unchanged in the Pub/Sub message this worker
                consumes (see so_import_worker.py's "poul-so-reprocess-buffer" handling).

Lifecycle:
  start_run()  → called once per attempt, right before processing begins. Idempotent:
                 on a Pub/Sub redelivery (same run_id, e.g. after a transient pre-fetch
                 failure), started_at is preserved from the first attempt so the UI's
                 elapsed timer doesn't appear to reset.
  finish_run() → called once the run reaches a terminal outcome — status "done" (ran to
                 completion, ack'd) or "error" (an unexpected exception escaped the run).
                 A transient failure that will be retried by Pub/Sub redelivery does NOT
                 call this — the doc is left at "processing" so the UI correctly keeps
                 showing "ongoing" through the retry.

All functions swallow their own exceptions and log a warning so a Firestore outage
never breaks the actual reprocess run.
"""
import logging
from datetime import datetime, timezone

from src import config

logger = logging.getLogger("reprocess_status")

_COLLECTION = f"reprocess_runs_{config.GCP_ENV.lower()}"

_db = None


def _client():
    global _db
    if _db is None:
        from google.cloud import firestore  # noqa: PLC0415 — lazy import avoids startup cost
        _db = firestore.Client(project=config.GCP_PROJECT_ID)
    return _db


def start_run(run_id: str, companies: list, notify: dict | None) -> None:
    if not run_id:
        return
    try:
        doc_ref = _client().collection(_COLLECTION).document(run_id)
        existing = doc_ref.get()
        payload = {
            "status": "processing",
            "companies": companies,
            "notify": notify or None,
            "updated_at": datetime.now(timezone.utc),
        }
        if not existing.exists:
            payload["started_at"] = datetime.now(timezone.utc)
        doc_ref.set(payload, merge=True)
        logger.info(f"reprocess_status: {run_id!r} -> processing (companies={companies})")
    except Exception as exc:
        logger.warning(f"reprocess_status: start_run failed for {run_id!r}: {exc}")


def finish_run(run_id: str, status: str, summary: dict, error: str | None = None) -> None:
    """status is 'done' or 'error'."""
    if not run_id:
        return
    try:
        _client().collection(_COLLECTION).document(run_id).set({
            "status": status,
            "summary": summary or {},
            "error": error,
            "finished_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        }, merge=True)
        logger.info(f"reprocess_status: {run_id!r} -> {status} (summary={summary})")
    except Exception as exc:
        logger.warning(f"reprocess_status: finish_run failed for {run_id!r}: {exc}")
